### In this section, I will prepare the data for modelling. I will preform the data modelling with base model, then results will be compared with further models, so we can monitor the improvement.

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
plt.style.use('seaborn')
import seaborn as sns

import re

import warnings
warnings.filterwarnings('ignore')

In [2]:
import time
start_time = time.time()

df_initial = pd.read_excel('Training_Combined_Data_v5.xlsx')
print("--- %s seconds ---" % (time.time() - start_time))

--- 130.04330444335938 seconds ---

In [3]:
df = df_initial.copy()

In [4]:
# display all rows and columns of the dataframe
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [5]:
df.head()

,Unnamed: 0,Unnamed: 0.1,host_since,host_response_time,host_response_rate,host_is_superhost,host_listings_count,host_identity_verified,neighbourhood_cleansed,market,country_code,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,availability_30,availability_60,availability_90,availability_365,number_of_reviews,review_scores_rating,review_scores_value,instant_bookable,cancellation_policy,price,host_days_active,air_conditioning,balcony,bed_linen,tv,coffee_machine,cooking_basics,white_goods,elevator,child_friendly,parking,host_greeting,hot_tub_sauna_or_pool,internet,long_term_stays,pets_allowed,private_entrance,smoking_allowed,distance,density,number_of_beds
0,0,0,2010-01-19,within an hour,90-99%,0,47,1,la Sagrada FamÃ­lia,Barcelona,ES,41.40420,2.17306,Apartment,Entire home/apt,8,2.0,3,6,150,50,2,30,1,1125,4,22,35,292,21,88,9,1,strict_14_with_grace_period,60,3470,1,0,0,1,0,0,1,1,1,1,1,0,1,0,0,0,0,2.124,15979.714,53
1,1,1,2010-03-09,within an hour,100%,1,5,1,el BesÃ²s i el Maresme,Barcelona,ES,41.41203,2.22114,Apartment,Entire home/apt,6,2.0,3,5,300,80,3,10,3,30,30,56,86,351,52,95,9,1,strict_14_with_grace_period,210,3421,0,1,1,1,1,1,1,1,1,1,1,0,1,1,0,0,0,4.982,15979.714,53
2,2,2,2010-06-02,within an hour,90-99%,0,41,0,el Camp d'en Grassot i GrÃ cia Nova,Barcelona,ES,41.40950,2.15938,Apartment,Entire home/apt,4,1.0,1,1,200,58,4,0,1,27,11,27,52,318,186,91,9,1,strict_14_with_grace_period,52,3336,1,0,0,1,0,0,1,1,0,0,0,0,1,0,0,0,0,2.954,15979.714,53
3,3,3,2010-06-02,within an hour,90-99%,0,41,0,el Camp d'en Grassot i GrÃ cia Nova,Barcelona,ES,41.40928,2.16112,Apartment,Entire home/apt,5,1.5,3,3,200,108,5,0,1,27,25,45,75,337,91,88,9,1,strict_14_with_grace_period,58,3336,1,0,0,1,0,0,1,1,0,0,0,0,1,0,0,0,0,2.877,15979.714,53
4,4,4,2010-06-09,within a day,100%,0,1,0,les Corts,Barcelona,ES,41.38720,2.14088,Apartment,Private room,1,1.0,1,1,0,20,1,15,29,60,4,4,24,83,19,99,9,0,moderate,35,3329,1,1,0,0,1,1,1,1,0,0,0,0,1,1,1,0,0,2.723,15979.714,53

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244641 entries, 0 to 244640
Data columns (total 56 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Unnamed: 0              244641 non-null  int64
 1   Unnamed: 0.1            244641 non-null  int64
 2   host_since              244641 non-null  datetime64[ns]
 3   host_response_time      244641 non-null  object
 4   host_response_rate      244641 non-null  object
 5   host_is_superhost       244641 non-null  int64
 6   host_listings_count     244641 non-null  int64
 7   host_identity_verified  244641 non-null  int64
 8   neighbourhood_cleansed  244641 non-null  object
 9   market                  244641 non-null  object
 10  country_code            244641 non-null  object
 11  latitude                244641 non-null  float64
 12  longitude               244641 non-null  float64
 13  property_type           244641 non-null  object
 14  room_type               244641 non-null  object
 15  accommodates            244641 non-null  int64
 16  bathrooms               244641 non-null  float64
 17  bedrooms                244641 non-null  int64
 18  beds                    244641 non-null  int64
 19  security_deposit        244641 non-null  int64
 20  cleaning_fee            244641 non-null  int64
 21  guests_included         244641 non-null  int64
 22  extra_people            244641 non-null  int64
 23  minimum_nights          244641 non-null  int64
 24  maximum_nights          244641 non-null  int64
 25  availability_30         244641 non-null  int64
 26  availability_60         244641 non-null  int64
 27  availability_90         244641 non-null  int64
 28  availability_365        244641 non-null  int64
 29  number_of_reviews       244641 non-null  int64
 30  review_scores_rating    244641 non-null  int64
 31  review_scores_value     244641 non-null  int64
 32  instant_bookable        244641 non-null  int64
 33  cancellation_policy     244641 non-null  object
 34  price                   244641 non-null  int64
 35  host_days_active        244641 non-null  int64
 36  air_conditioning        244641 non-null  int64
 37  balcony                 244641 non-null  int64
 38  bed_linen               244641 non-null  int64
 39  tv                      244641 non-null  int64
 40  coffee_machine          244641 non-null  int64
 41  cooking_basics          244641 non-null  int64
 42  white_goods             244641 non-null  int64
 43  elevator                244641 non-null  int64
 44  child_friendly          244641 non-null  int64
 45  parking                 244641 non-null  int64
 46  host_greeting           244641 non-null  int64
 47  hot_tub_sauna_or_pool   244641 non-null  int64
 48  internet                244641 non-null  int64
 49  long_term_stays         244641 non-null  int64
 50  pets_allowed            244641 non-null  int64
 51  private_entrance        244641 non-null  int64
 52  smoking_allowed         244641 non-null  int64
 53  distance                244641 non-null  float64
 54  density                 244641 non-null  float64
 55  number_of_beds          244641 non-null  int64
dtypes: datetime64[ns](1), float64(5), int64(42), object(8)
memory usage: 104.5+ MB

In [7]:
df.isnull().sum()

Unnamed: 0                0
Unnamed: 0.1              0
host_since                0
host_response_time        0
host_response_rate        0
host_is_superhost         0
host_listings_count       0
host_identity_verified    0
neighbourhood_cleansed    0
market                    0
country_code              0
latitude                  0
longitude                 0
property_type             0
room_type                 0
accommodates              0
bathrooms                 0
bedrooms                  0
beds                      0
security_deposit          0
cleaning_fee              0
guests_included           0
extra_people              0
minimum_nights            0
maximum_nights            0
availability_30           0
availability_60           0
availability_90           0
availability_365          0
number_of_reviews         0
review_scores_rating      0
review_scores_value       0
instant_bookable          0
cancellation_policy       0
price                     0
host_days_active          0
air_conditioning          0
balcony                   0
bed_linen                 0
tv                        0
coffee_machine            0
cooking_basics            0
white_goods               0
elevator                  0
child_friendly            0
parking                   0
host_greeting             0
hot_tub_sauna_or_pool     0
internet                  0
long_term_stays           0
pets_allowed              0
private_entrance          0
smoking_allowed           0
distance                  0
density                   0
number_of_beds            0
dtype: int64

In [8]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'host_since', 'host_response_time',
       'host_response_rate', 'host_is_superhost', 'host_listings_count',
       'host_identity_verified', 'neighbourhood_cleansed', 'market',
       'country_code', 'latitude', 'longitude', 'property_type', 'room_type',
       'accommodates', 'bathrooms', 'bedrooms', 'beds', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
       'maximum_nights', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'number_of_reviews',
       'review_scores_rating', 'review_scores_value', 'instant_bookable',
       'cancellation_policy', 'price', 'host_days_active', 'air_conditioning',
       'balcony', 'bed_linen', 'tv', 'coffee_machine', 'cooking_basics',
       'white_goods', 'elevator', 'child_friendly', 'parking', 'host_greeting',
       'hot_tub_sauna_or_pool', 'internet', 'long_term_stays', 'pets_allowed',
       'private_entrance', 'smoking_allowed', 'distance', 'density',
       'number_of_beds'],
      dtype='object')

droping uncesssary and redundant columns

In [9]:
df.drop(['Unnamed: 0', 'Unnamed: 0.1', 'host_since', 'host_response_time', 'neighbourhood_cleansed', 'country_code', \
         'latitude', 'longitude', 'availability_30', 'availability_365'], axis=1, inplace=True)

lets convert required columns as categorical datatype

In [10]:
for col in ['host_response_rate', 'market', 'property_type', 'room_type', 'cancellation_policy']:
    df[col] = df[col].astype('category')

lets convert required columns as boolean datatype

In [11]:
for col in ['host_is_superhost', 'host_identity_verified', 'instant_bookable', 'air_conditioning', 'balcony', 'bed_linen', 'tv', 'coffee_machine',
       'cooking_basics', 'white_goods', 'elevator', 'child_friendly',
       'parking', 'host_greeting', 'hot_tub_sauna_or_pool', 'internet', 'long_term_stays', 'pets_allowed', 'private_entrance', 
        'smoking_allowed']:
    df[col] = df[col].astype('bool')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244641 entries, 0 to 244640
Data columns (total 46 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   host_response_rate      244641 non-null  category
 1   host_is_superhost       244641 non-null  bool
 2   host_listings_count     244641 non-null  int64
 3   host_identity_verified  244641 non-null  bool
 4   market                  244641 non-null  category
 5   property_type           244641 non-null  category
 6   room_type               244641 non-null  category
 7   accommodates            244641 non-null  int64
 8   bathrooms               244641 non-null  float64
 9   bedrooms                244641 non-null  int64
 10  beds                    244641 non-null  int64
 11  security_deposit        244641 non-null  int64
 12  cleaning_fee            244641 non-null  int64
 13  guests_included         244641 non-null  int64
 14  extra_people            244641 non-null  int64
 15  minimum_nights          244641 non-null  int64
 16  maximum_nights          244641 non-null  int64
 17  availability_60         244641 non-null  int64
 18  availability_90         244641 non-null  int64
 19  number_of_reviews       244641 non-null  int64
 20  review_scores_rating    244641 non-null  int64
 21  review_scores_value     244641 non-null  int64
 22  instant_bookable        244641 non-null  bool
 23  cancellation_policy     244641 non-null  category
 24  price                   244641 non-null  int64
 25  host_days_active        244641 non-null  int64
 26  air_conditioning        244641 non-null  bool
 27  balcony                 244641 non-null  bool
 28  bed_linen               244641 non-null  bool
 29  tv                      244641 non-null  bool
 30  coffee_machine          244641 non-null  bool
 31  cooking_basics          244641 non-null  bool
 32  white_goods             244641 non-null  bool
 33  elevator                244641 non-null  bool
 34  child_friendly          244641 non-null  bool
 35  parking                 244641 non-null  bool
 36  host_greeting           244641 non-null  bool
 37  hot_tub_sauna_or_pool   244641 non-null  bool
 38  internet                244641 non-null  bool
 39  long_term_stays         244641 non-null  bool
 40  pets_allowed            244641 non-null  bool
 41  private_entrance        244641 non-null  bool
 42  smoking_allowed         244641 non-null  bool
 43  distance                244641 non-null  float64
 44  density                 244641 non-null  float64
 45  number_of_beds          244641 non-null  int64
dtypes: bool(20), category(5), float64(3), int64(18)
memory usage: 45.0 MB

seting target and features

In [13]:
target = df[['price']]

features = df.drop(['price'], axis = 1)

encoding the categorical variables

In [14]:
features.select_dtypes(include=['float64', 'int64', 'bool']).head()

,host_is_superhost,host_listings_count,host_identity_verified,accommodates,bathrooms,bedrooms,beds,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,availability_60,availability_90,number_of_reviews,review_scores_rating,review_scores_value,instant_bookable,host_days_active,air_conditioning,balcony,bed_linen,tv,coffee_machine,cooking_basics,white_goods,elevator,child_friendly,parking,host_greeting,hot_tub_sauna_or_pool,internet,long_term_stays,pets_allowed,private_entrance,smoking_allowed,distance,density,number_of_beds
0,False,47,True,8,2.0,3,6,150,50,2,30,1,1125,22,35,21,88,9,True,3470,True,False,False,True,False,False,True,True,True,True,True,False,True,False,False,False,False,2.124,15979.714,53
1,True,5,True,6,2.0,3,5,300,80,3,10,3,30,56,86,52,95,9,True,3421,False,True,True,True,True,True,True,True,True,True,True,False,True,True,False,False,False,4.982,15979.714,53
2,False,41,False,4,1.0,1,1,200,58,4,0,1,27,27,52,186,91,9,True,3336,True,False,False,True,False,False,True,True,False,False,False,False,True,False,False,False,False,2.954,15979.714,53
3,False,41,False,5,1.5,3,3,200,108,5,0,1,27,45,75,91,88,9,True,3336,True,False,False,True,False,False,True,True,False,False,False,False,True,False,False,False,False,2.877,15979.714,53
4,False,1,False,1,1.0,1,1,0,20,1,15,29,60,4,24,19,99,9,False,3329,True,True,False,False,True,True,True,True,False,False,False,False,True,True,True,False,False,2.723,15979.714,53

In [15]:
numerical_features = features.select_dtypes(include=['float64', 'int64', 'bool']).copy()

categorical_features = features.select_dtypes(include=['category']).copy()
categorical_features = pd.get_dummies(categorical_features)

In [16]:
encoded_features = pd.concat([numerical_features, categorical_features], axis=1)

In [17]:
encoded_features.shape

(244641, 61)

In [18]:
encoded_features.head()

,host_is_superhost,host_listings_count,host_identity_verified,accommodates,bathrooms,bedrooms,beds,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,availability_60,availability_90,number_of_reviews,review_scores_rating,review_scores_value,instant_bookable,host_days_active,air_conditioning,balcony,bed_linen,tv,coffee_machine,cooking_basics,white_goods,elevator,child_friendly,parking,host_greeting,hot_tub_sauna_or_pool,internet,long_term_stays,pets_allowed,private_entrance,smoking_allowed,distance,density,number_of_beds,host_response_rate_0-49%,host_response_rate_100%,host_response_rate_50-89%,host_response_rate_90-99%,host_response_rate_unknown,market_Barcelona,market_Berlin,market_Bologna,market_Munich,market_Naples,market_Porto,property_type_Apartment,property_type_House,property_type_Other,room_type_Entire home/apt,room_type_Hotel room,room_type_Private room,room_type_Shared room,cancellation_policy_flexible,cancellation_policy_moderate,cancellation_policy_strict_14_with_grace_period
0,False,47,True,8,2.0,3,6,150,50,2,30,1,1125,22,35,21,88,9,True,3470,True,False,False,True,False,False,True,True,True,True,True,False,True,False,False,False,False,2.124,15979.714,53,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1
1,True,5,True,6,2.0,3,5,300,80,3,10,3,30,56,86,52,95,9,True,3421,False,True,True,True,True,True,True,True,True,True,True,False,True,True,False,False,False,4.982,15979.714,53,0,1,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1
2,False,41,False,4,1.0,1,1,200,58,4,0,1,27,27,52,186,91,9,True,3336,True,False,False,True,False,False,True,True,False,False,False,False,True,False,False,False,False,2.954,15979.714,53,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1
3,False,41,False,5,1.5,3,3,200,108,5,0,1,27,45,75,91,88,9,True,3336,True,False,False,True,False,False,True,True,False,False,False,False,True,False,False,False,False,2.877,15979.714,53,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1
4,False,1,False,1,1.0,1,1,0,20,1,15,29,60,4,24,19,99,9,False,3329,True,True,False,False,True,True,True,True,False,False,False,False,True,True,True,False,False,2.723,15979.714,53,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0

In [19]:
encoded_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244641 entries, 0 to 244640
Data columns (total 61 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   host_is_superhost                                244641 non-null  bool
 1   host_listings_count                              244641 non-null  int64
 2   host_identity_verified                           244641 non-null  bool
 3   accommodates                                     244641 non-null  int64
 4   bathrooms                                        244641 non-null  float64
 5   bedrooms                                         244641 non-null  int64
 6   beds                                             244641 non-null  int64
 7   security_deposit                                 244641 non-null  int64
 8   cleaning_fee                                     244641 non-null  int64
 9   guests_included                                  244641 non-null  int64
 10  extra_people                                     244641 non-null  int64
 11  minimum_nights                                   244641 non-null  int64
 12  maximum_nights                                   244641 non-null  int64
 13  availability_60                                  244641 non-null  int64
 14  availability_90                                  244641 non-null  int64
 15  number_of_reviews                                244641 non-null  int64
 16  review_scores_rating                             244641 non-null  int64
 17  review_scores_value                              244641 non-null  int64
 18  instant_bookable                                 244641 non-null  bool
 19  host_days_active                                 244641 non-null  int64
 20  air_conditioning                                 244641 non-null  bool
 21  balcony                                          244641 non-null  bool
 22  bed_linen                                        244641 non-null  bool
 23  tv                                               244641 non-null  bool
 24  coffee_machine                                   244641 non-null  bool
 25  cooking_basics                                   244641 non-null  bool
 26  white_goods                                      244641 non-null  bool
 27  elevator                                         244641 non-null  bool
 28  child_friendly                                   244641 non-null  bool
 29  parking                                          244641 non-null  bool
 30  host_greeting                                    244641 non-null  bool
 31  hot_tub_sauna_or_pool                            244641 non-null  bool
 32  internet                                         244641 non-null  bool
 33  long_term_stays                                  244641 non-null  bool
 34  pets_allowed                                     244641 non-null  bool
 35  private_entrance                                 244641 non-null  bool
 36  smoking_allowed                                  244641 non-null  bool
 37  distance                                         244641 non-null  float64
 38  density                                          244641 non-null  float64
 39  number_of_beds                                   244641 non-null  int64
 40  host_response_rate_0-49%                         244641 non-null  uint8
 41  host_response_rate_100%                          244641 non-null  uint8
 42  host_response_rate_50-89%                        244641 non-null  uint8
 43  host_response_rate_90-99%                        244641 non-null  uint8
 44  host_response_rate_unknown                       244641 non-null  uint8
 45  market_Barcelona                                 244641 non-null  uint8
 46  market_Berlin                                    244641 non-null  uint8
 47  market_Bologna                                   244641 non-null  uint8
 48  market_Munich                                    244641 non-null  uint8
 49  market_Naples                                    244641 non-null  uint8
 50  market_Porto                                     244641 non-null  uint8
 51  property_type_Apartment                          244641 non-null  uint8
 52  property_type_House                              244641 non-null  uint8
 53  property_type_Other                              244641 non-null  uint8
 54  room_type_Entire home/apt                        244641 non-null  uint8
 55  room_type_Hotel room                             244641 non-null  uint8
 56  room_type_Private room                           244641 non-null  uint8
 57  room_type_Shared room                            244641 non-null  uint8
 58  cancellation_policy_flexible                     244641 non-null  uint8
 59  cancellation_policy_moderate                     244641 non-null  uint8
 60  cancellation_policy_strict_14_with_grace_period  244641 non-null  uint8
dtypes: bool(20), float64(3), int64(17), uint8(21)
memory usage: 46.9 MB

Split the data into traning and testing datesets

In [20]:
# used for splitinf the dataset
from sklearn.model_selection import train_test_split

# used for evaluating the models
from sklearn.metrics import mean_squared_error, r2_score

X_train, X_test, y_train, y_test = train_test_split(encoded_features, target, test_size = 0.25, random_state= 0)

Now we are ready for data modeling. In the next nootebook, I will start with linear, lasso and ridge regression. The model with best results will be selected as the base model.

In [21]:
df_modelling_data = pd.concat([encoded_features, target], axis=1)

In [22]:
df_modelling_data.to_excel('Training_Combined_Data_v6.xlsx')